### ISSUE TITLE
Ory proxy breaks API key / personal access tokens in privileged calls (e.g. identity management)

### ISSUE THREAD

**Issue by aeneasr** [ory/cli#298]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/cli/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/cli/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

See https://github.com/ory/cli/pull/296#issuecomment-1398388970

**Comment by tilschuenemann** [comment]
I've tested this running both `ory proxy http://localhost:3000/ $ORY_SDK_URL` and `ory proxy http://localhost:3000/ --dev` after updating the CLI to the newest version, `curl http://localhost:4000/.ory/admin/identities -H "Authorization:Bearer $ORY_API_KEY"` returns all identities for both cases therefore I think this issue got fixed by the tunnel fix as well.

**Comment by aeneasr** [comment]
Awesome! :)
